[2021-11-01 00:58:22,986] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.also_run_this manual__2021-11-01T00:58:21.385708+00:00 [queued]>
[2021-11-01 00:58:22,999] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.also_run_this manual__2021-11-01T00:58:21.385708+00:00 [queued]>
[2021-11-01 00:58:22,999] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-01 00:58:22,999] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-01 00:58:22,999] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-01 00:58:23,009] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): also_run_this> on 2021-11-01 00:58:21.385708+00:00
[2021-11-01 00:58:23,013] {standard_task_runner.py:52} INFO - Started process 1399 to run task
[2021-11-01 00:58:23,015] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'also_run_this', 'manual__2021-11-01T00:58:21.385708+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/checkModel.py', '--cfg-path', '/tmp/tmpwrd5ezni', '--error-file', '/tmp/tmpk4ou0pr0']
[2021-11-01 00:58:23,016] {standard_task_runner.py:77} INFO - Job 28: Subtask also_run_this
[2021-11-01 00:58:23,046] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.also_run_this manual__2021-11-01T00:58:21.385708+00:00 [running]> on host 7b304be9cff3
[2021-11-01 00:58:23,086] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2021-11-01T00:58:21.385708+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-01T00:58:21.385708+00:00
[2021-11-01 00:58:23,087] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-01 00:58:23,088] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'ls /opt/***']
[2021-11-01 00:58:23,097] {subprocess.py:85} INFO - Output:
[2021-11-01 00:58:23,099] {subprocess.py:89} INFO - ***-worker.pid
[2021-11-01 00:58:23,099] {subprocess.py:89} INFO - ***.cfg
[2021-11-01 00:58:23,100] {subprocess.py:89} INFO - dags
[2021-11-01 00:58:23,100] {subprocess.py:89} INFO - logs
[2021-11-01 00:58:23,100] {subprocess.py:89} INFO - mydata
[2021-11-01 00:58:23,100] {subprocess.py:89} INFO - plugins
[2021-11-01 00:58:23,100] {subprocess.py:89} INFO - webserver_config.py
[2021-11-01 00:58:23,100] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-01 00:58:23,120] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=also_run_this, execution_date=20211101T005821, start_date=20211101T005822, end_date=20211101T005823
[2021-11-01 00:58:23,147] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-01 00:58:23,169] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
